@startuml

class Color {
  name
  userId
}

class ColorController {
  searchColors()
  addColor()
  deleteColor()
}

class Database {
  query()
}

ColorController --> Database
Database --> Color

@enduml